import type { VisualStyle } from "@/types/preset";

export const STYLE_PRESETS: VisualStyle[] = [
  {
    id: "hand-drawn",
    name: "手绘简笔画",
    style: "手绘简笔画风格，柔软线条，轻松冷幽默，统一角色设计",
    colorScheme: "暖黄主色调，红橙色点缀，柔和明暗层次",
    backgroundStyle: "白色简约背景，搭配少量手绘街景或物件增强生活感",
    keywords: "手绘、简笔画、柔软线条、暖色调、轻松幽默",
    suitableFor: "搞笑、治愈、温情",
  },
  {
    id: "japanese-healing",
    name: "日系治愈插画",
    style: "日系清新治愈风插画，柔和透明水彩质感，温暖光线，梦幻氛围",
    colorScheme: "柔和粉彩色调，以淡粉、浅蓝、薄荷绿为主，明亮通透",
    backgroundStyle: "自然风景、小镇街角、温馨室内场景，大量留白空间",
    keywords: "日系、治愈、水彩、透明感、梦幻、自然光",
    suitableFor: "治愈、温情",
  },
  {
    id: "flat-vector",
    name: "扁平矢量漫画",
    style: "现代扁平化矢量风格，清晰轮廓线，纯色块填充，干净利落",
    colorScheme: "高饱和度的纯色组合，撞色搭配，视觉冲击力强",
    backgroundStyle: "几何化抽象背景，色块拼接，简约现代",
    keywords: "扁平设计、矢量、纯色块、清晰轮廓、现代感",
    suitableFor: "搞笑、励志",
  },
  {
    id: "ink-chinese",
    name: "水墨国风",
    style: "中国传统水墨画风格，浓淡干湿变化，留白意境，诗意表达",
    colorScheme: "黑白灰为主调，朱砂红/靛青/赭石点缀，水墨层次丰富",
    backgroundStyle: "山水云雾、庭院竹林、古风建筑，大量留白",
    keywords: "水墨、国风、留白、诗意、古典、禅意",
    suitableFor: "悬疑、温情、励志",
  },
  {
    id: "3d-cartoon",
    name: "3D卡通渲染",
    style: "三维卡通渲染风格，圆润造型，丰富材质纹理，立体光影",
    colorScheme: "鲜艳明亮的色彩，柔和阴影，环境光遮蔽效果",
    backgroundStyle: "带景深的3D场景，丰富细节和道具，真实光影",
    keywords: "3D、卡通、圆润、立体感、材质、光影",
    suitableFor: "搞笑、励志、治愈",
  },
  {
    id: "pixel-retro",
    name: "复古像素",
    style: "复古像素艺术风格，明显像素颗粒，有限色板，致敬经典游戏",
    colorScheme: "有限色板（16-32色），高对比度，霓虹色点缀",
    backgroundStyle: "像素化的场景，格状布局，游戏界面元素",
    keywords: "像素、复古、游戏风、色板限制、颗粒感",
    suitableFor: "搞笑、悬疑",
  },
  {
    id: "cyberpunk",
    name: "赛博朋克",
    style: "赛博朋克科幻风格，霓虹灯效，高科技低生活，暗黑都市氛围",
    colorScheme: "暗黑底色，霓虹紫/蓝/粉为主，高对比度光线",
    backgroundStyle: "未来都市夜景，全息投影，机械装置，雨夜街景",
    keywords: "赛博朋克、霓虹、科幻、暗黑都市、未来感",
    suitableFor: "悬疑、励志",
  },
  {
    id: "watercolor",
    name: "水彩手绘",
    style: "水彩手绘风格，颜色渗化晕染，透明层次，柔和的笔触纹理",
    colorScheme: "柔和渐变色，颜色自然过渡，淡雅清新",
    backgroundStyle: "淡彩渲染的背景，自然纹路，手工纸质感",
    keywords: "水彩、晕染、透明、手绘纹理、柔和",
    suitableFor: "治愈、温情",
  },
  {
    id: "nordic-minimal",
    name: "北欧极简",
    style: "北欧简约设计风格，几何造型，大面积留白，功能美学",
    colorScheme: "莫兰迪色系，低饱和度，大地色和柔和蓝灰调",
    backgroundStyle: "极简白色或浅灰背景，几何装饰元素，干净空间",
    keywords: "北欧、简约、几何、莫兰迪色、留白、功能性",
    suitableFor: "治愈、励志",
  },
  {
    id: "hk-neon",
    name: "港风霓虹",
    style: "香港霓虹灯牌风格，复古港味，密集视觉元素，市井烟火气",
    colorScheme: "深色夜幕底色，高饱和红/橙/绿霓虹灯色",
    backgroundStyle: "香港老街区，霓虹招牌林立，夜市摊位，狭窄街巷",
    keywords: "港风、霓虹灯、复古、市井、烟火气",
    suitableFor: "悬疑、搞笑",
  },
  {
    id: "children-book",
    name: "儿童绘本",
    style: "儿童绘本风格，可爱圆润角色，鲜艳色彩，图文结合叙事",
    colorScheme: "明亮鲜艳的原色，温暖且充满活力",
    backgroundStyle: "简洁可爱的场景，大色块背景，童趣元素",
    keywords: "儿童、绘本、可爱、圆润、鲜艳、童趣",
    suitableFor: "治愈、温情",
  },
  {
    id: "oil-painting",
    name: "油画质感",
    style: "油画风格，厚重笔触，丰富色彩层次，布面纹理质感",
    colorScheme: "古典油画色调，琥珀色/橄榄绿/深蓝，暖棕底调",
    backgroundStyle: "古典风景或室内场景，光影戏剧性，肌理丰富",
    keywords: "油画、笔触、布面纹理、古典、厚重",
    suitableFor: "悬疑、温情",
  },
  {
    id: "line-sketch",
    name: "线稿素描",
    style: "精细线稿素描风格，干净的铅笔线条，交叉排线阴影，单色表现",
    colorScheme: "黑白为主，偶有单色淡彩点缀（如淡棕或淡蓝）",
    backgroundStyle: "简洁或留白背景，线条引导视觉焦点",
    keywords: "素描、线稿、铅笔、排线、单色、精细",
    suitableFor: "悬疑、励志",
  },
  {
    id: "paper-cut",
    name: "剪纸风",
    style: "中国传统剪纸风格，层叠纸艺效果，镂空图案，民俗装饰纹样",
    colorScheme: "正红色为主，搭配金色/黑色，喜庆浓烈",
    backgroundStyle: "单色背景，剪纸层叠构成场景",
    keywords: "剪纸、镂空、民俗、层叠、红色、传统",
    suitableFor: "温情、励志",
  },
  {
    id: "ukiyoe",
    name: "日系浮世绘",
    style: "日本浮世绘风格，平面装饰性，流畅线条，渐变色彩",
    colorScheme: "靛蓝/朱红/藤黄/松绿等传统日本色",
    backgroundStyle: "和风场景，富士山/海浪/樱花/和室等元素",
    keywords: "浮世绘、日本、装饰性、平面、传统色",
    suitableFor: "悬疑、温情",
  },
  {
    id: "chibi",
    name: "Q版大头",
    style: "Q版大头卡通风格，超大头身比，夸张表情，迷你身体",
    colorScheme: "明亮粉嫩色彩，高光效果，卡通着色",
    backgroundStyle: "简化的卡通场景，可爱的装饰元素，对话框气泡",
    keywords: "Q版、大头、可爱、夸张表情、萌系",
    suitableFor: "搞笑、治愈",
  },
  {
    id: "american-comic",
    name: "美式漫画",
    style: "美式超级英雄漫画风格，粗犷线条，动态构图，拟声词特效",
    colorScheme: "高对比度原色，强烈阴影，网点印刷质感",
    backgroundStyle: "都市景观或科幻场景，速度线和爆炸效果",
    keywords: "美式、漫画、粗犷、动态、网点、超级英雄",
    suitableFor: "搞笑、励志",
  },
  {
    id: "gothic",
    name: "暗黑哥特",
    style: "哥特暗黑风格，华丽装饰细节，尖拱造型，神秘氛围",
    colorScheme: "深黑/暗紫/血红/银色，高对比暗调",
    backgroundStyle: "哥特教堂、古堡内部、月光下的墓园",
    keywords: "哥特、暗黑、华丽、神秘、尖拱、维多利亚",
    suitableFor: "悬疑",
  },
  {
    id: "pop-art",
    name: "波普艺术",
    style: "波普艺术风格，丝网印刷效果，网点放大，重复图案，流行文化元素",
    colorScheme: "高饱和原色，荧光色，强烈对比色块",
    backgroundStyle: "重复图案背景，拼贴元素，商业文化符号",
    keywords: "波普、丝网印刷、网点、荧光、流行文化、拼贴",
    suitableFor: "搞笑",
  },
  {
    id: "mori-kei",
    name: "森系清新",
    style: "森系小清新风格，自然元素，柔和光线，文艺氛围，植物环绕",
    colorScheme: "自然色系，草绿/木棕/米白/天空蓝",
    backgroundStyle: "森林、花园、阳光透过树叶的光斑、温馨木屋",
    keywords: "森系、自然、文艺、植物、清新、柔和光线",
    suitableFor: "治愈、温情",
  },
];
