- generic [active] [ref=e1]:
  - generic [ref=e2]:
    - banner [ref=e3]:
      - generic [ref=e4]:
        - heading "StoryCraft AI故事工坊" [level=1] [ref=e5]
        - paragraph [ref=e6]: AI故事图文创作助手 · Phase 2
      - generic [ref=e7]:
        - button "LLM 配置" [ref=e8] [cursor=pointer]:
          - img [ref=e9]
        - button "新建项目" [ref=e12] [cursor=pointer]
    - generic [ref=e14]:
      - paragraph [ref=e15]: ⚠️ 尚未配置 LLM API Key，请点击右上角齿轮图标 ⚙ 进行配置后使用 AI 功能
      - button "去配置" [ref=e16] [cursor=pointer]
    - main [ref=e17]:
      - generic [ref=e18]:
        - generic [ref=e19]:
          - generic [ref=e20]: "0"
          - heading "热点雷达" [level=3] [ref=e21]
          - generic [ref=e22]: A1/A2
        - generic [ref=e24]:
          - generic [ref=e25]:
            - generic [ref=e26]:
              - img [ref=e27]
              - generic [ref=e30]: 热点雷达
            - generic [ref=e31]:
              - generic [ref=e32]:
                - button "全部" [ref=e33] [cursor=pointer]
                - button "情感" [ref=e34] [cursor=pointer]
                - button "职场" [ref=e35] [cursor=pointer]
                - button "育儿" [ref=e36] [cursor=pointer]
                - button "宠物" [ref=e37] [cursor=pointer]
                - button "社会" [ref=e38] [cursor=pointer]
              - button "刷新热点" [ref=e39] [cursor=pointer]:
                - img [ref=e40]
                - text: 刷新热点
          - generic [ref=e46]:
            - paragraph [ref=e47]: 点击"刷新热点"获取当前热门话题
            - paragraph [ref=e48]: AI 将分析各平台热搜并推荐适合故事化创作的话题
      - generic [ref=e49]:
        - generic [ref=e50]:
          - generic [ref=e51]: "1"
          - heading "故事生成" [level=3] [ref=e52]
          - generic [ref=e53]: B1/B2
        - generic [ref=e55]:
          - generic [ref=e56]:
            - button "🤗 温情" [ref=e57] [cursor=pointer]
            - button "🕵️ 悬疑" [ref=e58] [cursor=pointer]
            - button "😂 搞笑" [ref=e59] [cursor=pointer]
            - button "🌿 治愈" [ref=e60] [cursor=pointer]
            - button "🔥 励志" [ref=e61] [cursor=pointer]
          - generic [ref=e63]:
            - generic [ref=e64]:
              - button "主题生成" [ref=e65] [cursor=pointer]:
                - img [ref=e66]
                - text: 主题生成
              - button "梗概扩展" [ref=e68] [cursor=pointer]:
                - img [ref=e69]
                - text: 梗概扩展
            - textbox "输入故事主题，例如：一只猫在城市里冒险..." [ref=e72]
            - generic [ref=e73]:
              - generic [ref=e74]: 当前风格：搞笑 · Ctrl+Enter 生成
              - button "生成故事" [disabled]
          - generic [ref=e75]: 请先输入主题，然后点击"生成故事"
  - alert [ref=e76]